import { getMenu } from '@/lib/api'
import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const menu = getMenu()

  return (
    <html lang="en">
      <body className="pl-[318px] pt-[18px]">
        <div className='pt-3 fixed w-[300px] h-screen left-0 top-0 bg-slate-400' >
          {
            menu.map((el) => {
              return (
                <div>
                  <div className='h-9 flex items-center pl-5'>
                    {Object.keys(el)}
                  </div>
                  <div className='pl-12 text-xm'>
                    {el[Object.keys(el)].map((nav) => {
                      return (
                        <Link href={`post/${nav.replace(/ /g, "_")}`}>
                          <div className='h-9 flex items-center'>
                            {nav}
                          </div>
                        </Link>
                      )
                    })}
                  </div>
                </div>
              )
            })
          }
        </div>
        <div className='mx-auto max-w-3xl'>
          {children}
        </div></body>
    </html>
  )
}
