import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="pl-[200px]"><div className='fixed border-x-white w-200px h-screen left-0' >
        test
      </div>{children}</body>
    </html>
  )
}
